name: XeLaTeX Resume to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup CTex
      run: sudo apt-get install texlive-lang-chinese
      
    - name: Install XeLaTeX
      run: sudo apt-get install texlive-xetex
    
    - name: Compile LaTeX
      run: |
        export PATH="/usr/local/texlive/2022/bin/x86_64-linux:$PATH"
        xelatex -interaction=nonstopmode resume-zh_CN.tex

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        user_name: hehansan
        user_email: hehansan@gintama.love
